#!/usr/bin/env bash

set -e

echo "Start on success"

# create output folders
mkdir -pv shippable/testresults
mkdir -pv shippable/codecoverage
mkdir -pv shippable/artifacts

# copy the output
if [ -d ./build/test-results ]; then echo "Copying test results"; cp -Rv ./build/test-results/* ./shippable/testresults; fi
if [ -d ./build/reports/cobertura ]; then echo "Copying cobertura results"; cp -Rv ./build/reports/cobertura/*.xml ./shippable/codecoverage; fi
if [ -d ./build/reports/jacoco/test ]; then echo "Copying jacoco results"; cp -Rv ./build/reports/jacoco/test/*.xml ./shippable/codecoverage; fi
if [ -d ./build/libs ]; then echo "Copying artifacts"; cp -Rv ./build/libs/* ./shippable/artifacts; fi

echo "End on success"
